### PR TITLE
update processorchain syntax in example

### PR DESCRIPTION
**Pull request by modosc**
see https://forum.juce.com/t/xcode-error-with-dsp-syntax/26433/21 - it took me a while to find this in the forums because i was copying from the example so i figured the example should be correct?

### CODE REVIEW

**Comment by modosc** [comment]
ping? i think this is still relevant.

**Comment by tpoole** [comment]
I can't reproduce the problem as described in the thread. Compiling the pre-PR code works as expected using Xcode 9 and any combination of base SDK and deployment target...

**Comment by modosc** [comment]
i'm on xcode 10, could that be part of the issue?

**Comment by modosc** [comment]
@tpoole figured it out - i'm using template values in my code:
```cpp
  dsp::ProcessorChain<dsp::ProcessorDuplicator<dsp::IIR::Filter<Type>,
                                               dsp::IIR::Coefficients<Type>>,
                      dsp::ProcessorDuplicator<dsp::IIR::Filter<Type>,
                                               dsp::IIR::Coefficients<Type>>>
      filterChain;
    auto &hpFilter = filterChain.get<0>();
    auto &lpFilter = filterChain.get<1>();
```

as-is i get this error:
```
Missing 'template' keyword prior to dependent template name 'get'
```

when i use this syntax it works:
```cpp
    auto &hpFilter = filterChain.template get<0>();
    auto &lpFilter = filterChain.template get<1>();
```

if i remove the templating then the other syntax works:
```cpp
  dsp::ProcessorChain<dsp::ProcessorDuplicator<dsp::IIR::Filter<float>,
                                               dsp::IIR::Coefficients<float>>,
                      dsp::ProcessorDuplicator<dsp::IIR::Filter<float>,
                                               dsp::IIR::Coefficients<float>>>
      filterChain;
    auto &hpFilter = filterChain.get<0>();
    auto &lpFilter = filterChain.get<1>();
```

since the dsp demo code isn't templated it works as-is so i'll close this out, sorry for the noise!

**Pull request closed without merging**
